# Generated by Django 3.2.3 on 2021-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_List', models.CharField(max_length=100, verbose_name='todo_list')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('isDone', models.BooleanField(default=False, verbose_name='isDone')),
                ('dead_Line', models.DateField(null=True, verbose_name='dead_Line')),
            ],
        ),
    ]
